# Generated by Django 5.2.8 on 2025-11-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hatvp", "0011_auto_20191218_0839"),
    ]

    operations = [
        migrations.AlterField(
            model_name="observation",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="hatvp.activity",
                verbose_name="activite_id",
            ),
        ),
    ]
